### ISSUE TITLE
Bot not showing icons

### ISSUE THREAD

**Issue by ShubhamKaudewar** [Sergetec/Wrdl-Bot#1]
![image](https://github.com/Sergetec/Wrdl-Bot/assets/38852978/620db307-587c-43c7-8d82-bd1c28978f64)

Hey Look at this image that bot not giving proper respective icon for word. This is issue still present

**Comment by sergiulefter** [comment]
The problem is not at my end, but at the permissions on your server or how you gave permissions to the bot when you invited it.
In order for Wrdl to have access to the emoji it uses to display words, it needs the "Use External Emoji" permission.
This permission is asked when you invite the bot (image below), but if you give it a role that does not have this permission (such as a Bot role with no permissions) then it will not have access.

Solution:
Either give @everyone access to "Use External Emoji" (tho I suppose you don't want that), or give the Bot role on your server access to "Use External Emoji".
![permission2](https://github.com/Sergetec/Wrdl-Bot/assets/96439803/4bb23045-cb51-4225-afff-9cca60b5cd96)
![permission1](https://github.com/Sergetec/Wrdl-Bot/assets/96439803/92b62d72-3294-4515-b51e-d82faf9d8421)

EDIT: I will move to only using images in the near future, so all of this emoji problem will not be a thing anymore.
